import LocalizedStrings from "react-localization";

let localizedStrings = new LocalizedStrings({
  en: {
    dian: "Diăn",
    home: "Home",
    menu: "Menu",
    images: "Images",
    manageMenu: "Manage Menu",
    manageImages: "Manage Images",
    addItems: "Add Items",
    editItems: "Edit Items",
    remove: "Remove",
    removeFromCart: "Remove from cart",
    removeItems: "Remove Items",
    finish: "Finish",
    food: "Food",
    drinks: "Drinks",
    photoAlbumHeader: "Photo Album Header",
    uploadImage: "Upload Image",
    itemInfoDivider: "Item Info",
    storeImage: "Store Image",
    imageGallery: "Image Gallery",
    schedule: "Schedule",
    updateShopSchedule: "Update Shop Schedule",
    confirmUpdate: "Confirm Update",
    orders: "Orders",
    scheduling: "Scheduling",
    settings: "Settings",
    manageMenu: "Manage Menu",
    openShop: "Open Shop",
    shopOpen: "Shop Open",
    open: "Open",
    closeShop: "Close Shop",
    shopClosed: "Shop Closed",
    closed: "Closed",
    confirm: "Confirm",
    reject: "Reject",
    delivery: "Delivery",
    deliveryAddress: "delivery address...",
    deliverySchedule: "Delivery Schedule",
    pickup: "Pickup",
    pickupSchedule: "Pickup Schedule",
    add: "Add",
    addDrink: "Add Drink",
    addFood: "Add Food",
    startTime: "Time - Start",
    endTime: "Time - End",
    pickATime: "Pick a time",
    bookmarkedAddresses: "Bookmarked Addresses...",
    cancel: "Cancel",
    ok: "Ok",
    location: "Location",
    locations: "Locations",
    removeLocation: "Remove Location",
    time: "Time",
    changeCredentials: "Change Credentials",
    signOut: "Sign Out",
    select: "Select",
    selectLanguage: "Select Language",
    english: "English",
    chinese: "Chinese",
    newEmail: "New Email",
    newPassword: "New Password",
    newPasswordConfirm: "New Password Confirm",
    pending: "Pending",
    confirmed: "Confirmed",
    delivered: "Delivered",
    rejected: "Rejected",
    inProgress: "In Progress",
    noOrdersFound: "No orders found...",
    confirmOrder: "Confirm the order",
    rejectOrder: "Reject the order",
    setOrderDeliveryInProgress: "Set order delivery in progress",
    setOrderDelivered: "Set order delivered",
    name: "Name",
    price: "Price",
    quantity: "Quantity",
    recipe: "Recipe (Optional)",
    recipeHeader: "Recipe",
    itemNameError: "*",
    itemPriceError: "*",
    itemQuantityError: "Quantity must be a positive whole number",
    submit: "Submit",
    displaySpinner: "Displaying ...",
    uploading: "Uploading...",
    noImage: "No Image Selected",
    storeFront: "Store Front",
    apply: "Apply",
    minOrder: "Min. Order",
    uploadedPictures: "Uploaded Pictures",
    chooseSchedule: "Please Choose Time & Location",
    upcoming: "Upcoming",
    pending: "Pending",
    customize: "Customize",
    soldOut: "0 left in stock - sold out",
    almostSoldOut: "left in stock - order soon",
    orderSoon: "order soon",
    qInCart: "Current quantity in cart:",
    kitchenClosedToday: "Kitchen is currently unavailable on this date",
    noTimesAvail: "Not available...",
    noteToChef: "Notes To Chef:",
    items: "Items",
    cart: "Cart",
    total: "Total",
    empty: "Empty",
    check: "Check",
    checkout: "Checkout",
    purchase: "Purchase",
    missingDetails1: "Missing delivery/pickup details.",
    missingDetails2: "Add details in Schedule section.",
    fee: "Fee"
  },
  zh: {
    dian: "Diăn",
    home: "主屏幕",
    menu: "菜谱",
    images: "图片",
    manageMenu: "管理菜谱",
    manageImages: "管理图片",
    addItems: "添加菜品",
    editItems: "更新菜品",
    removeItems: "删除菜品",
    remove: "清除",
    removeFromCart: "清除",
    finish: "确认",
    food: "食品",
    drinks: "饮料",
    photoAlbumHeader: "相册",
    uploadImage: "加载图片",
    itemInfoDivider: "Item Info (信息)",
    storeImage: "店面",
    imageGallery: "图片",
    schedule: "日程表",
    updateShopSchedule: "更新日程表",
    confirmUpdate: "确认",
    orders: "接单",
    scheduling: "日程表",
    settings: "设置",
    manageMenu: "菜谱",
    openShop: "开店",
    shopOpen: "营业中",
    open: "开店",
    closeShop: "关店",
    shopClosed: "休息中",
    closed: "关店",
    confirm: "接单",
    reject: "拒单",
    delivery: "已送到",
    deliveryAddress: "邮寄地址...",
    deliverySchedule: "外卖时间表",
    pickup: "提货",
    pickupSchedule: "提货时间表",
    add: "加",
    addDrink: "加饮料",
    addFood: "加食品",
    startTime: "开始时间",
    endTime: "结束时间",
    pickATime: "选择时间段",
    bookmarkedAddresses: "收藏的地址...",
    cancel: "取消",
    ok: "确认",
    location: "地点",
    locations: "地址",
    removeLocation: "删除地址",
    time: "时间",
    changeCredentials: "更改账号",
    signOut: "注销",
    select: "选择",
    selectLanguage: "选择语言",
    english: "英语",
    chinese: "中文",
    newEmail: "更新邮箱地址",
    newPassword: "更新密码",
    newPasswordConfirm: "确认密码",
    pending: "等待接单",
    confirmed: "已确认",
    delivered: "已送到",
    rejected: "拒单",
    inProgress: "进行中",
    noOrdersFound: "找不到订单...",
    confirmOrder: "接单",
    rejectOrder: "拒绝订单",
    setOrderDeliveryInProgress: "开启运输",
    setOrderDelivered: "订单已交付",
    name: "名称",
    price: "价格",
    quantity: "数量",
    recipe: "食譜 (Optional)",
    recipeHeader: "食譜",
    itemNameError: "*",
    itemPriceError: "*",
    itemQuantityError: "数量输入不对",
    submit: "提交",
    displaySpinner: "等待...",
    uploading: "上传中，请稍等...",
    noImage: "没有选",
    storeFront: "店面",
    apply: "确认",
    minOrder: "最低消费",
    uploadedPictures: "图片",
    chooseSchedule: "请选时间地点",
    upcoming: "即将来临",
    pending: "待定",
    customize: "定制",
    soldOut: "卖光了",
    almostSoldOut: "库存中还有",
    orderSoon: "个，请尽快订购",
    qInCart: "购物车数量:",
    kitchenClosedToday: "今天关上门",
    noTimesAvail: "无法使用...",
    noteToChef: "给厨师的提示:",
    items: "价钱",
    cart: "购物车",
    total: "价钱",
    empty: "空的",
    check: "校验",
    checkout: "结帐",
    purchase: "买",
    missingDetails1: "遗漏细节",
    missingDetails2: "按计划填写详细信息",
    fee: "费用"
  },
});

export default localizedStrings;
